name: "Flake Checks"
on:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v20


      - name: nix flake check
        run: nix flake check
  
  flake-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v20

      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@v10